import React from 'react';
import { StyleSheet } from 'react-native';
import {
  Activity,
  ArrowLeft,
  BarChart3,
  Bell,
  BookOpen,
  BookOpenCheck,
  Building2,
  BusFront,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CirclePlay,
  CircleCheck,
  CircleUserRound,
  CircleX,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  GraduationCap,
  Grid2x2,
  IdCard,
  KeyRound,
  Layers3,
  Library,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Moon,
  Navigation,
  Paperclip,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Search,
  ShieldCheck,
  SkipBack,
  SkipForward,
  Sun,
  Trash2,
  TrendingUp,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react-native';

const ICON_COMPONENTS = {
  Activity,
  ArrowLeft,
  BarChart3,
  Bell,
  BookOpen,
  BookOpenCheck,
  Building2,
  BusFront,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CirclePlay,
  CircleCheck,
  CircleUserRound,
  CircleX,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  GraduationCap,
  Grid2x2,
  IdCard,
  KeyRound,
  Layers3,
  Library,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Moon,
  Navigation,
  Paperclip,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Search,
  ShieldCheck,
  SkipBack,
  SkipForward,
  Sun,
  Trash2,
  TrendingUp,
  User,
  Users,
  X,
  Zap,
};

const ICON_MAP = {
  add: 'Plus',
  close: 'X',
  'chevron-back': 'ChevronLeft',
  'chevron-forward': 'ChevronRight',
  'chevron-down': 'ChevronDown',
  'chevron-up': 'ChevronUp',
  'arrow-back': 'ArrowLeft',
  'search-outline': 'Search',
  'notifications-outline': 'Bell',
  'log-out-outline': 'LogOut',
  'lock-closed-outline': 'Lock',
  'eye-outline': 'Eye',
  'eye-off-outline': 'EyeOff',
  'key-outline': 'KeyRound',
  'call-outline': 'Phone',
  'mail-outline': 'Mail',
  'calendar-outline': 'CalendarDays',
  'person-outline': 'User',
  'person-circle-outline': 'CircleUserRound',
  'people-outline': 'Users',
  'school-outline': 'GraduationCap',
  'library-outline': 'Library',
  'book-outline': 'BookOpen',
  'reader-outline': 'BookOpenCheck',
  'document-outline': 'File',
  'document-text-outline': 'FileText',
  'bus-outline': 'BusFront',
  'business-outline': 'Building2',
  'id-card-outline': 'IdCard',
  'megaphone-outline': 'Megaphone',
  'attach-outline': 'Paperclip',
  'download-outline': 'Download',
  'open-outline': 'ExternalLink',
  'create-outline': 'Pencil',
  'trash-outline': 'Trash2',
  'sync-outline': 'RefreshCw',
  'flash-outline': 'Zap',
  'funnel-outline': 'Filter',
  'play-skip-back-outline': 'SkipBack',
  'play-skip-forward-outline': 'SkipForward',
  'navigate-outline': 'Navigation',
  'bar-chart-outline': 'BarChart3',
  'card-outline': 'CreditCard',
  'shield-checkmark-outline': 'ShieldCheck',
  'ellipse-outline': 'Circle',
  'play-circle-outline': 'CirclePlay',
  'checkmark-circle': 'CircleCheck',
  'checkmark-circle-outline': 'CircleCheck',
  'checkmark-done-outline': 'CircleCheck',
  'close-circle-outline': 'CircleX',
  'layers-outline': 'Layers3',
  'grid-outline': 'Grid2x2',
  'pulse-outline': 'Activity',
  'trending-up-outline': 'TrendingUp',
  'moon-outline': 'Moon',
  'sunny-outline': 'Sun',
};

const FALLBACK_ICON = 'Circle';

export default function AppIcon({ name, size = 18, color, style, ...rest }) {
  const iconKey = ICON_MAP[name] || FALLBACK_ICON;
  const IconComponent = ICON_COMPONENTS[iconKey] || Circle;
  const flattened = StyleSheet.flatten(style) || {};
  const resolvedColor = color || flattened.color || '#2f4e70';
  const resolvedSize = Number(flattened.fontSize) || size;

  return (
    <IconComponent
      {...rest}
      size={resolvedSize}
      color={resolvedColor}
      strokeWidth={2}
      style={style}
    />
  );
}
